'use strict';

process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

/* --------------------------------- Imports -------------------------------- */
const fs = require('fs');
const path = require('path');
const { promisify } = require('util');
const { encode } = require('js-base64');
const paths = require('../config/paths');

/* --------------------------------- Globals -------------------------------- */
const readFile = promisify(fs.readFile);
const writeFile = promisify(fs.writeFile);
const INPUT_FILE = path.join('public', 'how-to.html');
const OUTPUT_FILE = path.join('src', 'config', 'HowToText.ts');

/* ------------------------------ Main Function ----------------------------- */
readFile(INPUT_FILE, 'utf8')
  .then((html) => {
    const content = `// THIS FILE IS AUTO-GENERATED BY NPM SCRIPT generate-howto\n// EDIT "PUBLIC/HOW-TO.HTML" TO CHANGE!
const html = \`${encode(html)}\`;
export default html;`;
    writeFile(OUTPUT_FILE, content, 'utf8')
      .then(() => {
        console.log('done');
      })
      .catch((err) => {
        console.error(err);
      });
  })
  .catch((err) => {
    console.error(err);
  });
